// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Recupera el estado de salud (nombre, URL, y estado) de todos los servicios registrados",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Obtiene el estado de todos los servicios",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/health/{name}": {
            "get": {
                "description": "Recupera el estado de salud de un servicio registrado por su nombre",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Obtiene el estado de un servicio específico",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nombre del servicio",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Microservice"
                        }
                    },
                    "404": {
                        "description": "Service not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/services": {
            "get": {
                "description": "Recupera una lista de todos los microservicios monitoreados en el sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "Obtiene todos los servicios registrados",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Microservice"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Registra un nuevo microservicio en el sistema de monitoreo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "Registra un nuevo servicio",
                "parameters": [
                    {
                        "description": "Datos del servicio",
                        "name": "service",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Microservice"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Microservice"
                        }
                    }
                }
            }
        },
        "/services/{name}": {
            "get": {
                "description": "Recupera los datos completos de un microservicio registrado por su nombre",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "Obtiene los datos de un servicio específico",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nombre del servicio",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Microservice"
                        }
                    },
                    "404": {
                        "description": "Service not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Modifica los datos de un microservicio registrado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "Actualiza un servicio existente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nombre del servicio",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos actualizados del servicio",
                        "name": "service",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Microservice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Microservice"
                        }
                    },
                    "500": {
                        "description": "Error al actualizar el microservicio",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un microservicio registrado del sistema de monitoreo",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "Elimina un servicio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nombre del servicio",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Microservicio eliminado exitosamente",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error al eliminar el microservicio",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Microservice": {
            "type": "object",
            "properties": {
                "emails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "endpoint": {
                    "type": "string"
                },
                "frequency": {
                    "description": "Frecuencia en segundos",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "description": "\"UP\" o \"DOWN\"",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "API de Monitoreo de Microservicios",
	Description:      "API para el monitoreo de estado de microservicios.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
